# Generated by Django 5.2.2 on 2025-06-20 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laptop',
            name='display',
            field=models.TextField(max_length=100),
        ),
    ]
