# Generated by Django 5.2.2 on 2025-06-20 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_app', '0002_alter_laptop_display'),
    ]

    operations = [
        migrations.AddField(
            model_name='laptop',
            name='brand',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
